### PR TITLE
removed warning cause be zero length array + CI

### PR DESCRIPTION
**Pull request by ravil-mobile**
Hi, this PR is addressed to remove a warning from SeisSol which propagates from this sub-modules cased by zero length array i.e.,  

```
template<TopoType Topo>
class Cell : public Element<int[0]>
{
	friend class PUML<Topo>;
	friend class Downward;

private:
	unsigned int m_vertices[internal::Topology<Topo>::cellvertices()];
};
```

I guess everything should be find wih std::array<int, 0>. 

I also changed compilation of tests from Scons to CMake. As far as I can see, the test only checks whether PUML2 can be compiled. I tried to execute the test but it asked for an input file which I don't know where to get one.

### CODE REVIEW

**Comment by sebwolf-de** [comment]
Code changes look good. SInce it was a C-Style array before, we just use `operator[]` on it, right? Other stuff might be undefined on zero-sized `std::array`s. 
About the CI: Older jobs just check for successful compilation. But it might still be interesting to get the tests working.

**Comment by sebwolf-de** [comment]
`puml.cpp` seems to read any of the SeisSol mesh files. There are no asserts, so I guess, it just checks if you encounter errors during the execution of a standard task.

**Comment by ravil-mobile** [comment]
Hi @sebwolf-de, thanks for your review

> Code changes look good. SInce it was a C-Style array before, we just use operator[] on it, right?

yes.

> But it might still be interesting to get the tests working.

As far as I understood, I need a mesh file for it. Do you have something in mind?

**Comment by ravil-mobile** [comment]
Hi again,  
A test with a small mesh and 2 MPI processes has been added. Shall we merge?

**Pull request merged**
